export const THEMES = {
    'vs-dark': {
        name: 'VS Code Dark',
        colors: {
            '--bg-darker': '#181818',
            '--bg-dark': '#1e1e1e',
            '--bg-sidebar': '#252526',
            '--bg-button': '#333333',
            '--bg-tab-inactive': '#2d2d2d',
            '--accent-color': '#007acc',
            '--accent-hover': '#1f8ad2',
            '--text-main': '#cccccc',
            '--text-muted': '#858585',
            '--border-color': '#3c3c3c',
            '--scrollbar-thumb': '#424242',
            '--scrollbar-thumb-hover': '#4f4f4f',
            '--syntax-comment': '#6a9955',
            '--syntax-doctype': '#569cd6',
            '--syntax-tag-name': '#569cd6',
            '--syntax-attr-name': '#9cdcfe',
            '--syntax-attr-value': '#ce9178',
            '--syntax-tag-bracket': '#808080',
            '--syntax-keyword': '#569cd6',
            '--syntax-string': '#ce9178',
            '--syntax-function': '#dcdcaa',
            '--syntax-builtin': '#4ec9b0',
            '--syntax-number': '#b5cea8',
            '--syntax-punctuation': '#d4d4d4',
            '--syntax-md-header': '#569cd6',
            '--syntax-md-list': '#9cdcfe',
            '--syntax-md-blockquote': '#6a9955',
            '--syntax-md-codeblock-fence': '#808080',
            '--syntax-md-codeblock-content': '#d4d4d4',
            '--syntax-md-bold': '#ce9178',
            '--syntax-md-italic': '#ce9178',
            '--syntax-md-inline-code': '#ce9178',
            '--syntax-md-link': '#4fc1ff'
        }
    },
    'dracula-intellij-light': {
        name: 'Dracula IntelliJ Light',
        colors: {
            '--bg-darker': '#f1f2f5',
            '--bg-dark': '#ffffff',
            '--bg-sidebar': '#f7f8fa',
            '--bg-button': '#ebecf0',
            '--bg-tab-inactive': '#f1f2f5',
            '--accent-color': '#3574f0',
            '--accent-hover': '#265ecc',
            '--text-main': '#1c1c1c',
            '--text-muted': '#808080',
            '--border-color': '#d1d4dc',
            '--scrollbar-thumb': '#d1d4dc',
            '--scrollbar-thumb-hover': '#b8bdc9',
            '--syntax-comment': '#8c8c8c',
            '--syntax-doctype': '#0033b3',
            '--syntax-tag-name': '#0033b3',
            '--syntax-attr-name': '#000000',
            '--syntax-attr-value': '#067d17',
            '--syntax-tag-bracket': '#1c1c1c',
            '--syntax-keyword': '#0033b3',
            '--syntax-string': '#067d17',
            '--syntax-function': '#00627a',
            '--syntax-builtin': '#0033b3',
            '--syntax-number': '#1750eb',
            '--syntax-punctuation': '#1c1c1c',
            '--syntax-md-header': '#0033b3',
            '--syntax-md-list': '#1750eb',
            '--syntax-md-blockquote': '#8c8c8c',
            '--syntax-md-codeblock-fence': '#8c8c8c',
            '--syntax-md-codeblock-content': '#1c1c1c',
            '--syntax-md-bold': '#1c1c1c',
            '--syntax-md-italic': '#1c1c1c',
            '--syntax-md-inline-code': '#067d17',
            '--syntax-md-link': '#1750eb'
        }
    },
    'dracula-intellij-dark': {
        name: 'Dracula IntelliJ Dark',
        colors: {
            '--bg-darker': '#1a1a1c',
            '--bg-dark': '#1e1f22',
            '--bg-sidebar': '#2b2d30',
            '--bg-button': '#393b40',
            '--bg-tab-inactive': '#2b2d30',
            '--accent-color': '#3574f0',
            '--accent-hover': '#4b89ff',
            '--text-main': '#ced0d6',
            '--text-muted': '#70737a',
            '--border-color': '#393b40',
            '--scrollbar-thumb': '#43454a',
            '--scrollbar-thumb-hover': '#4e5157',
            '--syntax-comment': '#7a7e85',
            '--syntax-doctype': '#cf8e6d',
            '--syntax-tag-name': '#e8bf6a',
            '--syntax-attr-name': '#bababa',
            '--syntax-attr-value': '#6aab73',
            '--syntax-tag-bracket': '#bababa',
            '--syntax-keyword': '#cf8e6d',
            '--syntax-string': '#6aab73',
            '--syntax-function': '#56a8f5',
            '--syntax-builtin': '#c77dbb',
            '--syntax-number': '#2aacb8',
            '--syntax-punctuation': '#ced0d6',
            '--syntax-md-header': '#cf8e6d',
            '--syntax-md-list': '#e8bf6a',
            '--syntax-md-blockquote': '#7a7e85',
            '--syntax-md-codeblock-fence': '#7a7e85',
            '--syntax-md-codeblock-content': '#ced0d6',
            '--syntax-md-bold': '#ced0d6',
            '--syntax-md-italic': '#ced0d6',
            '--syntax-md-inline-code': '#6aab73',
            '--syntax-md-link': '#56a8f5'
        }
    },
    'monokai': {
        name: 'Monokai Retro',
        colors: {
            '--bg-darker': '#191919',
            '--bg-dark': '#272822',
            '--bg-sidebar': '#1e1f1c',
            '--bg-button': '#3e3d32',
            '--bg-tab-inactive': '#22231f',
            '--accent-color': '#a6e22e',
            '--accent-hover': '#bde952',
            '--text-main': '#f8f8f2',
            '--text-muted': '#75715e',
            '--border-color': '#49483e',
            '--scrollbar-thumb': '#41423c',
            '--scrollbar-thumb-hover': '#75715e',
            '--syntax-comment': '#75715e',
            '--syntax-doctype': '#f92672',
            '--syntax-tag-name': '#f92672',
            '--syntax-attr-name': '#a6e22e',
            '--syntax-attr-value': '#e6db74',
            '--syntax-tag-bracket': '#f8f8f2',
            '--syntax-keyword': '#f92672',
            '--syntax-string': '#e6db74',
            '--syntax-function': '#66d9ef',
            '--syntax-builtin': '#a6e22e',
            '--syntax-number': '#ae81ff',
            '--syntax-punctuation': '#f8f8f2',
            '--syntax-md-header': '#f92672',
            '--syntax-md-list': '#a6e22e',
            '--syntax-md-blockquote': '#75715e',
            '--syntax-md-codeblock-fence': '#75715e',
            '--syntax-md-codeblock-content': '#f8f8f2',
            '--syntax-md-bold': '#e6db74',
            '--syntax-md-italic': '#e6db74',
            '--syntax-md-inline-code': '#e6db74',
            '--syntax-md-link': '#66d9ef'
        }
    },
    'github-light': {
        name: 'GitHub Light',
        colors: {
            '--bg-darker': '#f3f4f6',
            '--bg-dark': '#ffffff',
            '--bg-sidebar': '#f6f8fa',
            '--bg-button': '#eaeef2',
            '--bg-tab-inactive': '#eaeef2',
            '--accent-color': '#0969da',
            '--accent-hover': '#1a7fec',
            '--text-main': '#24292f',
            '--text-muted': '#57606a',
            '--border-color': '#d0d7de',
            '--scrollbar-thumb': '#d0d7de',
            '--scrollbar-thumb-hover': '#afb8c1',
            '--syntax-comment': '#6a737d',
            '--syntax-doctype': '#005cc5',
            '--syntax-tag-name': '#22863a',
            '--syntax-attr-name': '#6f42c1',
            '--syntax-attr-value': '#032f62',
            '--syntax-tag-bracket': '#24292f',
            '--syntax-keyword': '#d73a49',
            '--syntax-string': '#032f62',
            '--syntax-function': '#6f42c1',
            '--syntax-builtin': '#e36209',
            '--syntax-number': '#005cc5',
            '--syntax-punctuation': '#24292f',
            '--syntax-md-header': '#005cc5',
            '--syntax-md-list': '#24292f',
            '--syntax-md-blockquote': '#6a737d',
            '--syntax-md-codeblock-fence': '#959da5',
            '--syntax-md-codeblock-content': '#24292f',
            '--syntax-md-bold': '#24292f',
            '--syntax-md-italic': '#24292f',
            '--syntax-md-inline-code': '#032f62',
            '--syntax-md-link': '#005cc5'
        }
    },
    'solarized-dark': {
        name: 'Solarized Oceanic',
        colors: {
            '--bg-darker': '#00141a',
            '--bg-dark': '#002b36',
            '--bg-sidebar': '#073642',
            '--bg-button': '#0a4756',
            '--bg-tab-inactive': '#00212b',
            '--accent-color': '#2aa198',
            '--accent-hover': '#3fc4ba',
            '--text-main': '#93a1a1',
            '--text-muted': '#586e75',
            '--border-color': '#084d5e',
            '--scrollbar-thumb': '#073642',
            '--scrollbar-thumb-hover': '#586e75',
            '--syntax-comment': '#586e75',
            '--syntax-doctype': '#cb4b16',
            '--syntax-tag-name': '#268bd2',
            '--syntax-attr-name': '#b58900',
            '--syntax-attr-value': '#2aa198',
            '--syntax-tag-bracket': '#93a1a1',
            '--syntax-keyword': '#cb4b16',
            '--syntax-string': '#2aa198',
            '--syntax-function': '#268bd2',
            '--syntax-builtin': '#b58900',
            '--syntax-number': '#859900',
            '--syntax-punctuation': '#93a1a1',
            '--syntax-md-header': '#268bd2',
            '--syntax-md-list': '#b58900',
            '--syntax-md-blockquote': '#586e75',
            '--syntax-md-codeblock-fence': '#586e75',
            '--syntax-md-codeblock-content': '#93a1a1',
            '--syntax-md-bold': '#cb4b16',
            '--syntax-md-italic': '#cb4b16',
            '--syntax-md-inline-code': '#2aa198',
            '--syntax-md-link': '#268bd2'
        }
    },
    'roblox-studio-light': {
        name: 'Roblox Studio Light',
        colors: {
            '--bg-darker': '#e3e3e3',
            '--bg-dark': '#ffffff',
            '--bg-sidebar': '#f5f5f5',
            '--bg-button': '#dfdfdf',
            '--bg-tab-inactive': '#eeeeee',
            '--accent-color': '#0074cc',
            '--accent-hover': '#005999',
            '--text-main': '#000000',
            '--text-muted': '#7f7f7f',
            '--border-color': '#d3d3d3',
            '--scrollbar-thumb': '#cccccc',
            '--scrollbar-thumb-hover': '#b3b3b3',
            '--syntax-comment': '#008000',
            '--syntax-doctype': '#0000ff',
            '--syntax-tag-name': '#0000ff',
            '--syntax-attr-name': '#008080',
            '--syntax-attr-value': '#a31515',
            '--syntax-tag-bracket': '#000000',
            '--syntax-keyword': '#0000ff',
            '--syntax-string': '#a31515',
            '--syntax-function': '#008080',
            '--syntax-builtin': '#0000ff',
            '--syntax-number': '#09885a',
            '--syntax-punctuation': '#000000',
            '--syntax-md-header': '#0000ff',
            '--syntax-md-list': '#008080',
            '--syntax-md-blockquote': '#008000',
            '--syntax-md-codeblock-fence': '#008000',
            '--syntax-md-codeblock-content': '#000000',
            '--syntax-md-bold': '#09885a',
            '--syntax-md-italic': '#09885a',
            '--syntax-md-inline-code': '#a31515',
            '--syntax-md-link': '#0074cc'
        }
    },
    'roblox-studio-dark': {
        name: 'Roblox Studio Dark',
        colors: {
            '--bg-darker': '#1d1d1d',
            '--bg-dark': '#242424',
            '--bg-sidebar': '#2c2c2c',
            '--bg-button': '#333333',
            '--bg-tab-inactive': '#222222',
            '--accent-color': '#00a2ff',
            '--accent-hover': '#33b5ff',
            '--text-main': '#ffffff',
            '--text-muted': '#aaaaaa',
            '--border-color': '#3f3f3f',
            '--scrollbar-thumb': '#4f4f4f',
            '--scrollbar-thumb-hover': '#6f6f6f',
            '--syntax-comment': '#667289',
            '--syntax-doctype': '#f86d7c',
            '--syntax-tag-name': '#f86d7c',
            '--syntax-attr-name': '#84d6f7',
            '--syntax-attr-value': '#adf195',
            '--syntax-tag-bracket': '#cccccc',
            '--syntax-keyword': '#f86d7c',
            '--syntax-string': '#adf195',
            '--syntax-function': '#84d6f7',
            '--syntax-builtin': '#84d6f7',
            '--syntax-number': '#ffc600',
            '--syntax-punctuation': '#cccccc',
            '--syntax-md-header': '#f86d7c',
            '--syntax-md-list': '#84d6f7',
            '--syntax-md-blockquote': '#667289',
            '--syntax-md-codeblock-fence': '#667289',
            '--syntax-md-codeblock-content': '#ffffff',
            '--syntax-md-bold': '#ffc600',
            '--syntax-md-italic': '#ffc600',
            '--syntax-md-inline-code': '#adf195',
            '--syntax-md-link': '#00a2ff'
        }
    }
};

export function applyTheme(themeKey) {
    const theme = THEMES[themeKey];
    if (!theme) return;
    
    const rootStyles = document.documentElement.style;
    Object.entries(theme.colors).forEach(([variableName, hexValue]) => {
        rootStyles.setProperty(variableName, hexValue);
    });

    const indicator = document.getElementById('status-theme-indicator');
    if (indicator) {
        indicator.innerHTML = `<i class="fa-solid fa-palette"></i> Theme: ${theme.name}`;
    }
    
    localStorage.setItem('editor-theme-preset', themeKey);
}