export const PROSENSE_HTML = [
    // ==========================================
    // HTML TAGS
    // ==========================================
    
    // --- Root & Document Metadata ---
    { label: '!DOCTYPE', insertText: '!DOCTYPE html', type: 'tag' },
    { label: 'html', insertText: 'html lang="en"', type: 'tag' },
    { label: 'head', insertText: 'head', type: 'tag' },
    { label: 'title', insertText: 'title', type: 'tag' },
    { label: 'body', insertText: 'body', type: 'tag' },
    { label: 'meta:charset', insertText: 'meta charset="UTF-8"', type: 'tag' },
    { label: 'meta:viewport', insertText: 'meta name="viewport" content="width=device-width, initial-scale=1.0"', type: 'tag' },
    { label: 'meta:description', insertText: 'meta name="description" content=""', type: 'tag' },
    { label: 'link:css', insertText: 'link rel="stylesheet" href=""', type: 'tag' },
    { label: 'link:favicon', insertText: 'link rel="icon" type="image/x-icon" href=""', type: 'tag' },
    { label: 'base', insertText: 'base href=""', type: 'tag' },
    { label: 'noscript', insertText: 'noscript', type: 'tag' },

    // --- Document Structure & Layout ---
    { label: 'div', insertText: 'div', type: 'tag' },
    { label: 'span', insertText: 'span', type: 'tag' },
    { label: 'p', insertText: 'p', type: 'tag' },
    { label: 'a', insertText: 'a href=""', type: 'tag' },
    { label: 'button', insertText: 'button', type: 'tag' },
    { label: 'section', insertText: 'section', type: 'tag' },
    { label: 'article', insertText: 'article', type: 'tag' },
    { label: 'main', insertText: 'main', type: 'tag' },
    { label: 'header', insertText: 'header', type: 'tag' },
    { label: 'footer', insertText: 'footer', type: 'tag' },
    { label: 'nav', insertText: 'nav', type: 'tag' },
    { label: 'aside', insertText: 'aside', type: 'tag' },
    { label: 'search', insertText: 'search', type: 'tag' },
    { label: 'address', insertText: 'address', type: 'tag' },
    { label: 'details', insertText: 'details', type: 'tag' },
    { label: 'summary', insertText: 'summary', type: 'tag' },
    { label: 'dialog', insertText: 'dialog', type: 'tag' },
    
    // --- Headings ---
    { label: 'h1', insertText: 'h1', type: 'tag' },
    { label: 'h2', insertText: 'h2', type: 'tag' },
    { label: 'h3', insertText: 'h3', type: 'tag' },
    { label: 'h4', insertText: 'h4', type: 'tag' },
    { label: 'h5', insertText: 'h5', type: 'tag' },
    { label: 'h6', insertText: 'h6', type: 'tag' },
    
    // --- Forms & User Inputs ---
    { label: 'form', insertText: 'form action="" method="POST"', type: 'tag' },
    { label: 'label', insertText: 'label for=""', type: 'tag' },
    { label: 'input', insertText: 'input type="text"', type: 'tag' },
    { label: 'input:password', insertText: 'input type="password"', type: 'tag' },
    { label: 'input:email', insertText: 'input type="email"', type: 'tag' },
    { label: 'input:number', insertText: 'input type="number"', type: 'tag' },
    { label: 'input:checkbox', insertText: 'input type="checkbox"', type: 'tag' },
    { label: 'input:radio', insertText: 'input type="radio"', type: 'tag' },
    { label: 'input:file', insertText: 'input type="file"', type: 'tag' },
    { label: 'input:hidden', insertText: 'input type="hidden"', type: 'tag' },
    { label: 'input:search', insertText: 'input type="search"', type: 'tag' },
    { label: 'input:tel', insertText: 'input type="tel"', type: 'tag' },
    { label: 'input:url', insertText: 'input type="url"', type: 'tag' },
    { label: 'input:date', insertText: 'input type="date"', type: 'tag' },
    { label: 'input:time', insertText: 'input type="time"', type: 'tag' },
    { label: 'input:datetime-local', insertText: 'input type="datetime-local"', type: 'tag' },
    { label: 'input:color', insertText: 'input type="color"', type: 'tag' },
    { label: 'input:range', insertText: 'input type="range"', type: 'tag' },
    { label: 'input:submit', insertText: 'input type="submit" value=""', type: 'tag' },
    { label: 'input:button', insertText: 'input type="button" value=""', type: 'tag' },
    { label: 'input:image', insertText: 'input type="image" src="" alt=""', type: 'tag' },
    { label: 'textarea', insertText: 'textarea name="" id="" cols="30" rows="10"', type: 'tag' },
    { label: 'select', insertText: 'select name="" id=""', type: 'tag' },
    { label: 'option', insertText: 'option value=""', type: 'tag' },
    { label: 'optgroup', insertText: 'optgroup label=""', type: 'tag' },
    { label: 'datalist', insertText: 'datalist id=""', type: 'tag' },
    { label: 'fieldset', insertText: 'fieldset', type: 'tag' },
    { label: 'legend', insertText: 'legend', type: 'tag' },
    { label: 'output', insertText: 'output', type: 'tag' },
    { label: 'progress', insertText: 'progress value="" max=""', type: 'tag' },
    { label: 'meter', insertText: 'meter value="" min="" max=""', type: 'tag' },
    
    // --- Lists ---
    { label: 'ul', insertText: 'ul', type: 'tag' },
    { label: 'ol', insertText: 'ol', type: 'tag' },
    { label: 'li', insertText: 'li', type: 'tag' },
    { label: 'dl', insertText: 'dl', type: 'tag' },
    { label: 'dt', insertText: 'dt', type: 'tag' },
    { label: 'dd', insertText: 'dd', type: 'tag' },
    
    // --- Tables ---
    { label: 'table', insertText: 'table', type: 'tag' },
    { label: 'thead', insertText: 'thead', type: 'tag' },
    { label: 'tbody', insertText: 'tbody', type: 'tag' },
    { label: 'tfoot', insertText: 'tfoot', type: 'tag' },
    { label: 'tr', insertText: 'tr', type: 'tag' },
    { label: 'th', insertText: 'th', type: 'tag' },
    { label: 'td', insertText: 'td', type: 'tag' },
    { label: 'caption', insertText: 'caption', type: 'tag' },
    { label: 'colgroup', insertText: 'colgroup', type: 'tag' },
    { label: 'col', insertText: 'col', type: 'tag' },
    
    // --- Inline Text Formatting & Semantics ---
    { label: 'strong', insertText: 'strong', type: 'tag' },
    { label: 'em', insertText: 'em', type: 'tag' },
    { label: 'code', insertText: 'code', type: 'tag' },
    { label: 'pre', insertText: 'pre', type: 'tag' },
    { label: 'small', insertText: 'small', type: 'tag' },
    { label: 'sub', insertText: 'sub', type: 'tag' },
    { label: 'sup', insertText: 'sup', type: 'tag' },
    { label: 'br', insertText: 'br /', type: 'tag' },
    { label: 'hr', insertText: 'hr /', type: 'tag' },
    { label: 'blockquote', insertText: 'blockquote', type: 'tag' },
    { label: 'abbr', insertText: 'abbr title=""', type: 'tag' },
    { label: 'bdi', insertText: 'bdi', type: 'tag' },
    { label: 'bdo', insertText: 'bdo dir="rtl"', type: 'tag' },
    { label: 'cite', insertText: 'cite', type: 'tag' },
    { label: 'data_tag', insertText: 'data value=""', type: 'tag' },
    { label: 'time', insertText: 'time datetime=""', type: 'tag' },
    { label: 'dfn', insertText: 'dfn', type: 'tag' },
    { label: 'kbd', insertText: 'kbd', type: 'tag' },
    { label: 'mark', insertText: 'mark', type: 'tag' },
    { label: 'q', insertText: 'q', type: 'tag' },
    { label: 's', insertText: 's', type: 'tag' },
    { label: 'samp', insertText: 'samp', type: 'tag' },
    { label: 'u', insertText: 'u', type: 'tag' },
    { label: 'var', insertText: 'var', type: 'tag' },
    { label: 'wbr', insertText: 'wbr /', type: 'tag' },
    { label: 'del', insertText: 'del', type: 'tag' },
    { label: 'ins', insertText: 'ins', type: 'tag' },
    
    // --- Embedded Media & Graphics ---
    { label: 'img', insertText: 'img src="" alt=""', type: 'tag' },
    { label: 'video', insertText: 'video src="" controls', type: 'tag' },
    { label: 'audio', insertText: 'audio src="" controls', type: 'tag' },
    { label: 'picture', insertText: 'picture', type: 'tag' },
    { label: 'source', insertText: 'source srcset="" type=""', type: 'tag' },
    { label: 'canvas', insertText: 'canvas id="" width="" height=""', type: 'tag' },
    { label: 'svg', insertText: 'svg width="" height="" viewBox="0 0  "', type: 'tag' },
    { label: 'iframe', insertText: 'iframe src="" frameborder="0"', type: 'tag' },
    { label: 'embed', insertText: 'embed src="" type=""', type: 'tag' },
    { label: 'object', insertText: 'object data="" type=""', type: 'tag' },
    { label: 'param', insertText: 'param name="" value=""', type: 'tag' },
    { label: 'track', insertText: 'track src="" kind="" srclang="" label=""', type: 'tag' },
    { label: 'map', insertText: 'map name=""', type: 'tag' },
    { label: 'area', insertText: 'area shape="" coords="" href="" alt=""', type: 'tag' },
    
    // --- Web Components & Templates ---
    { label: 'template', insertText: 'template', type: 'tag' },
    { label: 'slot', insertText: 'slot name=""', type: 'tag' },
    
    // --- Scripts & Styling ---
    { label: 'style', insertText: 'style', type: 'tag' },
    { label: 'script', insertText: 'script', type: 'tag' },
    { label: 'script:src', insertText: 'script src=""', type: 'tag' },

    // ==========================================
    // HTML ATTRIBUTES
    // ==========================================
    
    // --- Global Attributes ---
    { label: 'class', insertText: 'class=""', type: 'attribute' },
    { label: 'id', insertText: 'id=""', type: 'attribute' },
    { label: 'title', insertText: 'title=""', type: 'attribute' },
    { label: 'style_attr', insertText: 'style=""', type: 'attribute' },
    { label: 'tabindex', insertText: 'tabindex="0"', type: 'attribute' },
    { label: 'contenteditable', insertText: 'contenteditable="true"', type: 'attribute' },
    { label: 'hidden', insertText: 'hidden', type: 'attribute' },
    { label: 'data', insertText: 'data-=""', type: 'attribute' },
    { label: 'lang', insertText: 'lang="en"', type: 'attribute' },
    { label: 'dir', insertText: 'dir="rtl"', type: 'attribute' },
    { label: 'draggable', insertText: 'draggable="true"', type: 'attribute' },
    { label: 'spellcheck', insertText: 'spellcheck="true"', type: 'attribute' },
    { label: 'accesskey', insertText: 'accesskey=""', type: 'attribute' },
    { label: 'autocapitalize', insertText: 'autocapitalize="sentences"', type: 'attribute' },
    
    // --- Links, Images & Media ---
    { label: 'href', insertText: 'href=""', type: 'attribute' },
    { label: 'src', insertText: 'src=""', type: 'attribute' },
    { label: 'alt', insertText: 'alt=""', type: 'attribute' },
    { label: 'target', insertText: 'target="_blank"', type: 'attribute' },
    { label: 'rel', insertText: 'rel="noopener noreferrer"', type: 'attribute' },
    { label: 'download', insertText: 'download', type: 'attribute' },
    { label: 'loading', insertText: 'loading="lazy"', type: 'attribute' },
    { label: 'srcset', insertText: 'srcset=""', type: 'attribute' },
    { label: 'sizes', insertText: 'sizes=""', type: 'attribute' },
    { label: 'controls', insertText: 'controls', type: 'attribute' },
    { label: 'autoplay', insertText: 'autoplay', type: 'attribute' },
    { label: 'loop', insertText: 'loop', type: 'attribute' },
    { label: 'muted', insertText: 'muted', type: 'attribute' },
    { label: 'poster', insertText: 'poster=""', type: 'attribute' },
    { label: 'preload', insertText: 'preload="auto"', type: 'attribute' },
    { label: 'crossorigin', insertText: 'crossorigin="anonymous"', type: 'attribute' },
    
    // --- Form Specific & Validation ---
    { label: 'type', insertText: 'type=""', type: 'attribute' },
    { label: 'name', insertText: 'name=""', type: 'attribute' },
    { label: 'value', insertText: 'value=""', type: 'attribute' },
    { label: 'placeholder', insertText: 'placeholder=""', type: 'attribute' },
    { label: 'autocomplete', insertText: 'autocomplete="off"', type: 'attribute' },
    { label: 'action', insertText: 'action=""', type: 'attribute' },
    { label: 'method', insertText: 'method="POST"', type: 'attribute' },
    { label: 'enctype', insertText: 'enctype="multipart/form-data"', type: 'attribute' },
    { label: 'pattern', insertText: 'pattern=""', type: 'attribute' },
    { label: 'min', insertText: 'min=""', type: 'attribute' },
    { label: 'max', insertText: 'max=""', type: 'attribute' },
    { label: 'step', insertText: 'step=""', type: 'attribute' },
    { label: 'maxlength', insertText: 'maxlength=""', type: 'attribute' },
    { label: 'minlength', insertText: 'minlength=""', type: 'attribute' },
    { label: 'rows', insertText: 'rows=""', type: 'attribute' },
    { label: 'cols', insertText: 'cols=""', type: 'attribute' },
    { label: 'for', insertText: 'for=""', type: 'attribute' },
    { label: 'list_attr', insertText: 'list=""', type: 'attribute' },
    { label: 'accept', insertText: 'accept=""', type: 'attribute' },
    { label: 'capture', insertText: 'capture="user"', type: 'attribute' },
    
    // --- Boolean Form Attributes ---
    { label: 'disabled', insertText: 'disabled', type: 'attribute' },
    { label: 'required', insertText: 'required', type: 'attribute' },
    { label: 'readonly', insertText: 'readonly', type: 'attribute' },
    { label: 'checked', insertText: 'checked', type: 'attribute' },
    { label: 'selected', insertText: 'selected', type: 'attribute' },
    { label: 'multiple', insertText: 'multiple', type: 'attribute' },
    { label: 'autofocus', insertText: 'autofocus', type: 'attribute' },
    { label: 'novalidate', insertText: 'novalidate', type: 'attribute' },
    
    // --- Script & Asset Security ---
    { label: 'async', insertText: 'async', type: 'attribute' },
    { label: 'defer', insertText: 'defer', type: 'attribute' },
    { label: 'integrity', insertText: 'integrity=""', type: 'attribute' },
    { label: 'referrerpolicy', insertText: 'referrerpolicy="no-referrer"', type: 'attribute' },
    
    // --- Accessibility (ARIA) ---
    { label: 'role', insertText: 'role=""', type: 'attribute' },
    { label: 'aria-label', insertText: 'aria-label=""', type: 'attribute' },
    { label: 'aria-labelledby', insertText: 'aria-labelledby=""', type: 'attribute' },
    { label: 'aria-describedby', insertText: 'aria-describedby=""', type: 'attribute' },
    { label: 'aria-hidden', insertText: 'aria-hidden="true"', type: 'attribute' },
    { label: 'aria-expanded', insertText: 'aria-expanded="false"', type: 'attribute' },
    { label: 'aria-live', insertText: 'aria-live="polite"', type: 'attribute' },
    { label: 'aria-checked', insertText: 'aria-checked="false"', type: 'attribute' },
    { label: 'aria-disabled', insertText: 'aria-disabled="true"', type: 'attribute' },
    { label: 'aria-controls', insertText: 'aria-controls=""', type: 'attribute' },
    { label: 'aria-haspopup', insertText: 'aria-haspopup="true"', type: 'attribute' },
    { label: 'aria-modal', insertText: 'aria-modal="true"', type: 'attribute' },
    { label: 'aria-required', insertText: 'aria-required="true"', type: 'attribute' },
    { label: 'aria-selected', insertText: 'aria-selected="false"', type: 'attribute' }
];