export const PROSENSE_CSS = [
    // ==========================================
    // CSS PROPERTIES
    // ==========================================
    
    // --- Colors & Backgrounds ---
    { label: 'color', insertText: 'color: ', type: 'property' },
    { label: 'background', insertText: 'background: ', type: 'property' },
    { label: 'background-color', insertText: 'background-color: ', type: 'property' },
    { label: 'background-image', insertText: 'background-image: url();', type: 'property' },
    { label: 'background-size', insertText: 'background-size: cover;', type: 'property' },
    { label: 'background-position', insertText: 'background-position: center;', type: 'property' },
    { label: 'background-repeat', insertText: 'background-repeat: no-repeat;', type: 'property' },
    { label: 'background-attachment', insertText: 'background-attachment: fixed;', type: 'property' },
    { label: 'background-clip', insertText: 'background-clip: padding-box;', type: 'property' },
    { label: 'background-origin', insertText: 'background-origin: border-box;', type: 'property' },
    { label: 'background-blend-mode', insertText: 'background-blend-mode: normal;', type: 'property' },
    { label: 'opacity', insertText: 'opacity: ', type: 'property' },
    { label: 'mix-blend-mode', insertText: 'mix-blend-mode: ', type: 'property' },
    { label: 'color-scheme', insertText: 'color-scheme: dark light;', type: 'property' },

    // --- Box Model (Spacing & Sizing) ---
    { label: 'margin', insertText: 'margin: ', type: 'property' },
    { label: 'margin-top', insertText: 'margin-top: ', type: 'property' },
    { label: 'margin-right', insertText: 'margin-right: ', type: 'property' },
    { label: 'margin-bottom', insertText: 'margin-bottom: ', type: 'property' },
    { label: 'margin-left', insertText: 'margin-left: ', type: 'property' },
    { label: 'padding', insertText: 'padding: ', type: 'property' },
    { label: 'padding-top', insertText: 'padding-top: ', type: 'property' },
    { label: 'padding-right', insertText: 'padding-right: ', type: 'property' },
    { label: 'padding-bottom', insertText: 'padding-bottom: ', type: 'property' },
    { label: 'padding-left', insertText: 'padding-left: ', type: 'property' },
    { label: 'width', insertText: 'width: ', type: 'property' },
    { label: 'height', insertText: 'height: ', type: 'property' },
    { label: 'min-width', insertText: 'min-width: ', type: 'property' },
    { label: 'max-width', insertText: 'max-width: ', type: 'property' },
    { label: 'min-height', insertText: 'min-height: ', type: 'property' },
    { label: 'max-height', insertText: 'max-height: ', type: 'property' },
    { label: 'box-sizing', insertText: 'box-sizing: border-box;', type: 'property' },
    { label: 'aspect-ratio', insertText: 'aspect-ratio: ', type: 'property' },
    { label: 'overflow', insertText: 'overflow: hidden;', type: 'property' },
    { label: 'overflow-x', insertText: 'overflow-x: ', type: 'property' },
    { label: 'overflow-y', insertText: 'overflow-y: ', type: 'property' },
    { label: 'object-fit', insertText: 'object-fit: cover;', type: 'property' },
    { label: 'object-position', insertText: 'object-position: center;', type: 'property' },

    // --- Logical Properties (Modern CSS Layouts) ---
    { label: 'margin-block', insertText: 'margin-block: ', type: 'property' },
    { label: 'margin-block-start', insertText: 'margin-block-start: ', type: 'property' },
    { label: 'margin-block-end', insertText: 'margin-block-end: ', type: 'property' },
    { label: 'margin-inline', insertText: 'margin-inline: ', type: 'property' },
    { label: 'margin-inline-start', insertText: 'margin-inline-start: ', type: 'property' },
    { label: 'margin-inline-end', insertText: 'margin-inline-end: ', type: 'property' },
    { label: 'padding-block', insertText: 'padding-block: ', type: 'property' },
    { label: 'padding-block-start', insertText: 'padding-block-start: ', type: 'property' },
    { label: 'padding-block-end', insertText: 'padding-block-end: ', type: 'property' },
    { label: 'padding-inline', insertText: 'padding-inline: ', type: 'property' },
    { label: 'padding-inline-start', insertText: 'padding-inline-start: ', type: 'property' },
    { label: 'padding-inline-end', insertText: 'padding-inline-end: ', type: 'property' },
    { label: 'inline-size', insertText: 'inline-size: ', type: 'property' },
    { label: 'block-size', insertText: 'block-size: ', type: 'property' },
    { label: 'min-inline-size', insertText: 'min-inline-size: ', type: 'property' },
    { label: 'max-inline-size', insertText: 'max-inline-size: ', type: 'property' },
    { label: 'min-block-size', insertText: 'min-block-size: ', type: 'property' },
    { label: 'max-block-size', insertText: 'max-block-size: ', type: 'property' },
    { label: 'inset', insertText: 'inset: 0;', type: 'property' },
    { label: 'inset-block', insertText: 'inset-block: ', type: 'property' },
    { label: 'inset-inline', insertText: 'inset-inline: ', type: 'property' },

    // --- Borders & Shadows ---
    { label: 'border', insertText: 'border: 1px solid ', type: 'property' },
    { label: 'border-top', insertText: 'border-top: ', type: 'property' },
    { label: 'border-right', insertText: 'border-right: ', type: 'property' },
    { label: 'border-bottom', insertText: 'border-bottom: ', type: 'property' },
    { label: 'border-left', insertText: 'border-left: ', type: 'property' },
    { label: 'border-width', insertText: 'border-width: ', type: 'property' },
    { label: 'border-style', insertText: 'border-style: ', type: 'property' },
    { label: 'border-color', insertText: 'border-color: ', type: 'property' },
    { label: 'border-radius', insertText: 'border-radius: ', type: 'property' },
    { label: 'border-image', insertText: 'border-image: ', type: 'property' },
    { label: 'box-shadow', insertText: 'box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);', type: 'property' },
    { label: 'text-shadow', insertText: 'text-shadow: ', type: 'property' },
    { label: 'outline', insertText: 'outline: ', type: 'property' },
    { label: 'outline-offset', insertText: 'outline-offset: ', type: 'property' },

    // --- Layout & Positioning ---
    { label: 'display', insertText: 'display: ', type: 'property' },
    { label: 'position', insertText: 'position: ', type: 'property' },
    { label: 'top', insertText: 'top: ', type: 'property' },
    { label: 'right', insertText: 'right: ', type: 'property' },
    { label: 'bottom', insertText: 'bottom: ', type: 'property' },
    { label: 'left', insertText: 'left: ', type: 'property' },
    { label: 'z-index', insertText: 'z-index: ', type: 'property' },
    { label: 'float', insertText: 'float: ', type: 'property' },
    { label: 'clear', insertText: 'clear: ', type: 'property' },
    { label: 'visibility', insertText: 'visibility: ', type: 'property' },
    { label: 'clip-path', insertText: 'clip-path: ', type: 'property' },
    { label: 'isolation', insertText: 'isolation: isolate;', type: 'property' },
    { label: 'contain', insertText: 'contain: ', type: 'property' },
    { label: 'content-visibility', insertText: 'content-visibility: auto;', type: 'property' },

    // --- Container Queries ---
    { label: 'container', insertText: 'container: name / inline-size;', type: 'property' },
    { label: 'container-type', insertText: 'container-type: inline-size;', type: 'property' },
    { label: 'container-name', insertText: 'container-name: ', type: 'property' },

    // --- Flexbox ---
    { label: 'flex', insertText: 'flex: ', type: 'property' },
    { label: 'flex-grow', insertText: 'flex-grow: ', type: 'property' },
    { label: 'flex-shrink', insertText: 'flex-shrink: ', type: 'property' },
    { label: 'flex-basis', insertText: 'flex-basis: ', type: 'property' },
    { label: 'flex-direction', insertText: 'flex-direction: column;', type: 'property' },
    { label: 'flex-wrap', insertText: 'flex-wrap: wrap;', type: 'property' },
    { label: 'flex-flow', insertText: 'flex-flow: ', type: 'property' },
    { label: 'justify-content', insertText: 'justify-content: ', type: 'property' },
    { label: 'align-items', insertText: 'align-items: ', type: 'property' },
    { label: 'align-content', insertText: 'align-content: ', type: 'property' },
    { label: 'align-self', insertText: 'align-self: ', type: 'property' },
    { label: 'order', insertText: 'order: ', type: 'property' },
    { label: 'gap', insertText: 'gap: ', type: 'property' },
    { label: 'row-gap', insertText: 'row-gap: ', type: 'property' },
    { label: 'column-gap', insertText: 'column-gap: ', type: 'property' },

    // --- Grid ---
    { label: 'grid', insertText: 'grid: ', type: 'property' },
    { label: 'grid-template-columns', insertText: 'grid-template-columns: repeat(3, 1fr);', type: 'property' },
    { label: 'grid-template-rows', insertText: 'grid-template-rows: ', type: 'property' },
    { label: 'grid-template-areas', insertText: 'grid-template-areas: ', type: 'property' },
    { label: 'grid-auto-columns', insertText: 'grid-auto-columns: ', type: 'property' },
    { label: 'grid-auto-rows', insertText: 'grid-auto-rows: ', type: 'property' },
    { label: 'grid-auto-flow', insertText: 'grid-auto-flow: ', type: 'property' },
    { label: 'grid-column', insertText: 'grid-column: ', type: 'property' },
    { label: 'grid-column-start', insertText: 'grid-column-start: ', type: 'property' },
    { label: 'grid-column-end', insertText: 'grid-column-end: ', type: 'property' },
    { label: 'grid-row', insertText: 'grid-row: ', type: 'property' },
    { label: 'grid-row-start', insertText: 'grid-row-start: ', type: 'property' },
    { label: 'grid-row-end', insertText: 'grid-row-end: ', type: 'property' },
    { label: 'grid-area', insertText: 'grid-area: ', type: 'property' },
    { label: 'place-items', insertText: 'place-items: center;', type: 'property' },
    { label: 'place-content', insertText: 'place-content: ', type: 'property' },
    { label: 'place-self', insertText: 'place-self: ', type: 'property' },

    // --- Typography & Text Properties ---
    { label: 'font', insertText: 'font: ', type: 'property' },
    { label: 'font-size', insertText: 'font-size: ', type: 'property' },
    { label: 'font-family', insertText: 'font-family: ', type: 'property' },
    { label: 'font-weight', insertText: 'font-weight: ', type: 'property' },
    { label: 'font-style', insertText: 'font-style: italic;', type: 'property' },
    { label: 'font-display', insertText: 'font-display: swap;', type: 'property' },
    { label: 'font-variant', insertText: 'font-variant: ', type: 'property' },
    { label: 'line-height', insertText: 'line-height: ', type: 'property' },
    { label: 'text-align', insertText: 'text-align: ', type: 'property' },
    { label: 'text-align-last', insertText: 'text-align-last: ', type: 'property' },
    { label: 'text-transform', insertText: 'text-transform: uppercase;', type: 'property' },
    { label: 'text-decoration', insertText: 'text-decoration: none;', type: 'property' },
    { label: 'text-decoration-line', insertText: 'text-decoration-line: ', type: 'property' },
    { label: 'text-decoration-style', insertText: 'text-decoration-style: ', type: 'property' },
    { label: 'text-decoration-color', insertText: 'text-decoration-color: ', type: 'property' },
    { label: 'text-underline-offset', insertText: 'text-underline-offset: ', type: 'property' },
    { label: 'text-indent', insertText: 'text-indent: ', type: 'property' },
    { label: 'letter-spacing', insertText: 'letter-spacing: ', type: 'property' },
    { label: 'word-spacing', insertText: 'word-spacing: ', type: 'property' },
    { label: 'white-space', insertText: 'white-space: nowrap;', type: 'property' },
    { label: 'text-overflow', insertText: 'text-overflow: ellipsis;', type: 'property' },
    { label: 'word-break', insertText: 'word-break: break-word;', type: 'property' },
    { label: 'overflow-wrap', insertText: 'overflow-wrap: break-word;', type: 'property' },
    { label: 'vertical-align', insertText: 'vertical-align: middle;', type: 'property' },
    { label: 'list-style', insertText: 'list-style: none;', type: 'property' },
    { label: 'list-style-type', insertText: 'list-style-type: ', type: 'property' },
    { label: 'list-style-position', insertText: 'list-style-position: ', type: 'property' },
    { label: 'text-rendering', insertText: 'text-rendering: optimizeLegibility;', type: 'property' },
    { label: '-webkit-font-smoothing', insertText: '-webkit-font-smoothing: antialiased;', type: 'property' },

    // --- UI, Interaction, Scrolling & Control ---
    { label: 'cursor', insertText: 'cursor: pointer;', type: 'property' },
    { label: 'user-select', insertText: 'user-select: none;', type: 'property' },
    { label: 'pointer-events', insertText: 'pointer-events: none;', type: 'property' },
    { label: 'scroll-behavior', insertText: 'scroll-behavior: smooth;', type: 'property' },
    { label: 'scroll-snap-type', insertText: 'scroll-snap-type: y mandatory;', type: 'property' },
    { label: 'scroll-snap-align', insertText: 'scroll-snap-align: center;', type: 'property' },
    { label: 'scroll-margin', insertText: 'scroll-margin: ', type: 'property' },
    { label: 'scroll-padding', insertText: 'scroll-padding: ', type: 'property' },
    { label: 'overscroll-behavior', insertText: 'overscroll-behavior: contain;', type: 'property' },
    { label: 'accent-color', insertText: 'accent-color: ', type: 'property' },
    { label: 'caret-color', insertText: 'caret-color: ', type: 'property' },
    { label: 'resize', insertText: 'resize: both;', type: 'property' },
    { label: 'touch-action', insertText: 'touch-action: manipulation;', type: 'property' },
    { label: 'will-change', insertText: 'will-change: transform, opacity;', type: 'property' },

    // --- Transitions, Animations & Filters ---
    { label: 'transition', insertText: 'transition: all 0.3s ease;', type: 'property' },
    { label: 'transition-property', insertText: 'transition-property: ', type: 'property' },
    { label: 'transition-duration', insertText: 'transition-duration: ', type: 'property' },
    { label: 'transition-timing-function', insertText: 'transition-timing-function: ', type: 'property' },
    { label: 'transition-delay', insertText: 'transition-delay: ', type: 'property' },
    { label: 'transform', insertText: 'transform: ', type: 'property' },
    { label: 'transform-origin', insertText: 'transform-origin: center;', type: 'property' },
    { label: 'transform-style', insertText: 'transform-style: preserve-3d;', type: 'property' },
    { label: 'perspective', insertText: 'perspective: ', type: 'property' },
    { label: 'backface-visibility', insertText: 'backface-visibility: hidden;', type: 'property' },
    { label: 'animation', insertText: 'animation: name duration timing-function delay iteration-count direction fill-mode;', type: 'property' },
    { label: 'animation-name', insertText: 'animation-name: ', type: 'property' },
    { label: 'animation-duration', insertText: 'animation-duration: ', type: 'property' },
    { label: 'animation-timing-function', insertText: 'animation-timing-function: ', type: 'property' },
    { label: 'animation-delay', insertText: 'animation-delay: ', type: 'property' },
    { label: 'animation-iteration-count', insertText: 'animation-iteration-count: infinite;', type: 'property' },
    { label: 'animation-direction', insertText: 'animation-direction: alternate;', type: 'property' },
    { label: 'animation-fill-mode', insertText: 'animation-fill-mode: forwards;', type: 'property' },
    { label: 'animation-play-state', insertText: 'animation-play-state: paused;', type: 'property' },
    { label: 'filter', insertText: 'filter: blur() brightness();', type: 'property' },
    { label: 'backdrop-filter', insertText: 'backdrop-filter: blur(10px);', type: 'property' },
    { label: 'mask-image', insertText: 'mask-image: url();', type: 'property' },

    // ==========================================
    // CSS PSEUDO-CLASSES & ELEMENTS
    // ==========================================
    { label: ':hover', insertText: ':hover {\n  \n}', type: 'snippet' },
    { label: ':focus', insertText: ':focus {\n  \n}', type: 'snippet' },
    { label: ':focus-visible', insertText: ':focus-visible {\n  \n}', type: 'snippet' },
    { label: ':focus-within', insertText: ':focus-within {\n  \n}', type: 'snippet' },
    { label: ':active', insertText: ':active {\n  \n}', type: 'snippet' },
    { label: ':visited', insertText: ':visited {\n  \n}', type: 'snippet' },
    { label: ':disabled', insertText: ':disabled {\n  \n}', type: 'snippet' },
    { label: ':checked', insertText: ':checked {\n  \n}', type: 'snippet' },
    { label: ':required', insertText: ':required {\n  \n}', type: 'snippet' },
    { label: ':valid', insertText: ':valid {\n  \n}', type: 'snippet' },
    { label: ':invalid', insertText: ':invalid {\n  \n}', type: 'snippet' },
    { label: ':placeholder-shown', insertText: ':placeholder-shown {\n  \n}', type: 'snippet' },
    { label: ':nth-child', insertText: ':nth-child() {\n  \n}', type: 'snippet' },
    { label: ':nth-last-child', insertText: ':nth-last-child() {\n  \n}', type: 'snippet' },
    { label: ':nth-of-type', insertText: ':nth-of-type() {\n  \n}', type: 'snippet' },
    { label: ':first-child', insertText: ':first-child {\n  \n}', type: 'snippet' },
    { label: ':last-child', insertText: ':last-child {\n  \n}', type: 'snippet' },
    { label: ':first-of-type', insertText: ':first-of-type {\n  \n}', type: 'snippet' },
    { label: ':last-of-type', insertText: ':last-of-type {\n  \n}', type: 'snippet' },
    { label: ':only-child', insertText: ':only-child {\n  \n}', type: 'snippet' },
    { label: ':empty', insertText: ':empty {\n  \n}', type: 'snippet' },
    { label: ':not', insertText: ':not() {\n  \n}', type: 'snippet' },
    { label: ':is', insertText: ':is() {\n  \n}', type: 'snippet' },
    { label: ':where', insertText: ':where() {\n  \n}', type: 'snippet' },
    { label: ':has', insertText: ':has() {\n  \n}', type: 'snippet' },
    { label: '::before', insertText: '::before {\n  content: "";\n  position: absolute;\n  \n}', type: 'snippet' },
    { label: '::after', insertText: '::after {\n  content: "";\n  position: absolute;\n  \n}', type: 'snippet' },
    { label: '::placeholder', insertText: '::placeholder {\n  \n}', type: 'snippet' },
    { label: '::selection', insertText: '::selection {\n  \n}', type: 'snippet' },
    { label: '::marker', insertText: '::marker {\n  \n}', type: 'snippet' },
    { label: '::first-line', insertText: '::first-line {\n  \n}', type: 'snippet' },
    { label: '::first-letter', insertText: '::first-letter {\n  \n}', type: 'snippet' },

    // ==========================================
    // CSS FUNCTIONS
    // ==========================================
    { label: 'calc()', insertText: 'calc()', type: 'snippet' },
    { label: 'clamp()', insertText: 'clamp()', type: 'snippet' },
    { label: 'min()', insertText: 'min()', type: 'snippet' },
    { label: 'max()', insertText: 'max()', type: 'snippet' },
    { label: 'var()', insertText: 'var(--)', type: 'snippet' },
    { label: 'rgba()', insertText: 'rgba(0, 0, 0, )', type: 'snippet' },
    { label: 'hsla()', insertText: 'hsla(0, 0%, 0%, )', type: 'snippet' },
    { label: 'linear-gradient()', insertText: 'linear-gradient(to right, , )', type: 'snippet' },
    { label: 'radial-gradient()', insertText: 'radial-gradient(circle, , )', type: 'snippet' },
    { label: 'conic-gradient()', insertText: 'conic-gradient(from 0deg, , )', type: 'snippet' },
    { label: 'url()', insertText: 'url("")', type: 'snippet' },

    // ==========================================
    // QUICK SNIPPETS & BOILERPLATES
    // ==========================================
    { label: 'display: flex', insertText: 'display: flex;', type: 'snippet' },
    { label: 'display: grid', insertText: 'display: grid;', type: 'snippet' },
    { label: 'position: absolute', insertText: 'position: absolute;', type: 'snippet' },
    { label: 'position: relative', insertText: 'position: relative;', type: 'snippet' },
    { label: 'flex-center', insertText: 'display: flex;\njustify-content: center;\nalign-items: center;', type: 'snippet' },
    { label: 'flex-column-center', insertText: 'display: flex;\nflex-direction: column;\njustify-content: center;\nalign-items: center;', type: 'snippet' },
    { label: 'grid-center', insertText: 'display: grid;\nplace-items: center;', type: 'snippet' },
    { label: 'grid-auto-fit', insertText: 'display: grid;\ngrid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\ngap: 1rem;', type: 'snippet' },
    { label: 'grid-auto-fill', insertText: 'display: grid;\ngrid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\ngap: 1rem;', type: 'snippet' },
    { label: 'absolute-center', insertText: 'position: absolute;\ntop: 50%;\nleft: 50%;\ntransform: translate(-50%, -50%);', type: 'snippet' },
    { label: 'inset-center', insertText: 'position: absolute;\ninset: 0;\nmargin: auto;', type: 'snippet' },
    { label: 'text-truncate', insertText: 'overflow: hidden;\nwhite-space: nowrap;\ntext-overflow: ellipsis;', type: 'snippet' },
    { label: 'text-clamp', insertText: 'display: -webkit-box;\n-webkit-line-clamp: 3;\n-webkit-box-orient: vertical;\noverflow: hidden;', type: 'snippet' },
    { label: 'scrollbar-hide', insertText: 'scrollbar-width: none;\n&::-webkit-scrollbar {\n  display: none;\n}', type: 'snippet' },
    
    // --- Modern Reset & Base At-Rules ---
    { label: 'css-reset', insertText: '*, *::before, *::after {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}', type: 'snippet' },
    { label: 'css-variables', insertText: ':root {\n  --primary: #3490dc;\n  --secondary: #ffed4a;\n  --bg: #ffffff;\n  --text: #333333;\n}', type: 'snippet' },
    { label: 'media-mobile', insertText: '@media (max-width: 480px) {\n  \n}', type: 'snippet' },
    { label: 'media-tablet', insertText: '@media (max-width: 768px) {\n  \n}', type: 'snippet' },
    { label: 'media-desktop', insertText: '@media (max-width: 1024px) {\n  \n}', type: 'snippet' },
    { label: 'media-dark-mode', insertText: '@media (prefers-color-scheme: dark) {\n  \n}', type: 'snippet' },
    { label: 'media-reduce-motion', insertText: '@media (prefers-reduced-motion: reduce) {\n  \n}', type: 'snippet' },
    { label: 'container-query', insertText: '@container (min-width: 400px) {\n  \n}', type: 'snippet' },
    { label: 'keyframes', insertText: '@keyframes fadeIn {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}', type: 'snippet' },
    { label: 'supports', insertText: '@supports (display: grid) {\n  \n}', type: 'snippet' },
    { label: 'layer', insertText: '@layer base, components, utilities;', type: 'snippet' },
    { label: 'property-rule', insertText: '@property --my-var {\n  syntax: "<color>";\n  inherits: false;\n  initial-value: #000;\n}', type: 'snippet' }
];