export function setupProjectTools(ctx) {
    // 1. Toolbar Button: Generate standard Python project
    ctx.addToolbarButton('new-python-project', 'New Python Project', 'fa-solid fa-cube', async () => {
        const response = await ctx.showCustomModal({
            title: "Create Python Project",
            inputs: [
                { id: "projectName", label: "Project/Directory Name", type: "text", defaultValue: "my_python_app" }
            ],
            okLabel: "Generate Project",
            cancelLabel: "Cancel"
        });

        if (!response) return;
        const projectName = response.projectName;

        const result = await ctx.createProjectStructure({
            folders: ['src', 'tests', 'docs'],
            files: {
                'src/main.py': `def main():\n    print("Hello from Pythonix IDE! 🐍")\n\nif __name__ == "__main__":\n    main()\n`,
                'tests/test_main.py': `import unittest\n\nclass TestMain(unittest.TestCase):\n    def test_sample(self):\n        self.assertEqual(True, True)\n\nif __name__ == '__main__':\n    unittest.main()\n`,
                'README.md': `# ${projectName}\n\nA Python project created with Pro Code Editor.`
            }
        });

        if (result && result.success && result.files['src/main.py']) {
            await ctx.openFile(result.files['src/main.py']);
        }
    });

    // 2. Toolbar Button: Environment configurator tool
    ctx.addToolbarButton('python-config', 'Python Setup', 'fa-solid fa-sliders', async () => {
        const results = await ctx.showCustomModal({
            title: "Python Environment Config",
            inputs: [
                { id: "pythonVersion", label: "Target Python Version", type: "select", options: ["Python 3.10", "Python 3.11", "Python 3.12"], defaultValue: "Python 3.11" },
                { id: "useVirtualEnv", label: "Generate requirements.txt", type: "checkbox", defaultValue: true }
            ],
            okLabel: "Save Config",
            cancelLabel: "Cancel"
        });

        if (!results) return;

        await ctx.createProjectStructure({
            folders: [],
            files: {
                'requirements.txt': `# Generated by Pythonix IDE Setup\n# Target: ${results.pythonVersion}\n`
            }
        });

        await ctx.showCustomModal({
            title: "Configuration Saved",
            inputs: [],
            okLabel: "Acknowledged",
            cancelLabel: ""
        });
    });

    // 3. Toolbar Button: Trigger to open the Pythonix IDE sidebar and focus Scratchpad section
    ctx.addToolbarButton('open-scratchpad-panel', 'Scratchpad', 'fa-brands fa-python', () => {
        // The dynamic Activity Bar button rendered by the core for our sidebar panel.
        const tab = document.getElementById('act-btn-pythonix-ide-panel');
        if (!tab) return;

        const sidebar = document.getElementById('sidebar');
        const alreadyOpen = tab.classList.contains('active') &&
                            sidebar && !sidebar.classList.contains('collapsed-bar');

        // Clicking the activity button toggles/collapses when the panel is already the
        // active view, so only click when we actually need to open or expand it.
        if (!alreadyOpen) tab.click();

        // Dispatch a custom event so the sidebar panel focuses the Scratchpad accordion.
        // The panel is rendered into #sidebar-plugin-content, which is where the listener lives.
        setTimeout(() => {
            const panel = document.getElementById('sidebar-plugin-content');
            if (panel) {
                panel.dispatchEvent(new CustomEvent('open-scratchpad-accordion'));
            }
        }, 60);
    });
}