export function setupProjectTools(ctx) {
    // Generate Python project structure
    ctx.addToolbarButton('new-python-project', 'New Python Project', 'fa-solid fa-cube', async () => {
        // Replace prompt() with a custom modal widget popup
        const response = await ctx.showCustomModal({
            title: "Create Python Project",
            inputs: [
                { id: "projectName", label: "Project/Directory Name", type: "text", defaultValue: "my_python_app" }
            ],
            okLabel: "Generate Project",
            cancelLabel: "Cancel"
        });

        if (!response) return;
        const projectName = response.projectName;

        const result = await ctx.createProjectStructure({
            folders: ['src', 'tests', 'docs'],
            files: {
                'src/main.py': `def main():\n    print("Hello from Python Developer IDE! 🐍")\n\nif __name__ == "__main__":\n    main()\n`,
                'tests/test_main.py': `import unittest\n\nclass TestMain(unittest.TestCase):\n    def test_sample(self):\n        self.assertEqual(True, True)\n\nif __name__ == '__main__':\n    unittest.main()\n`,
                'README.md': `# ${projectName}\n\nA Python project created with Pro Code Editor.`
            }
        });

        if (result && result.success && result.files['src/main.py']) {
            await ctx.openFile(result.files['src/main.py']);
        }
    });

    // Environment configurator tool
    ctx.addToolbarButton('python-config', 'Python Setup', 'fa-solid fa-sliders', async () => {
        const results = await ctx.showCustomModal({
            title: "Python Environment Config",
            inputs: [
                { id: "pythonVersion", label: "Target Python Version", type: "select", options: ["Python 3.10", "Python 3.11", "Python 3.12"], defaultValue: "Python 3.11" },
                { id: "useVirtualEnv", label: "Generate requirements.txt", type: "checkbox", defaultValue: true }
            ],
            okLabel: "Save Config",
            cancelLabel: "Cancel"
        });

        if (!results) return;

        await ctx.createProjectStructure({
            folders: [],
            files: {
                'requirements.txt': `# Generated by Python IDE Setup\n# Target: ${results.pythonVersion}\n`
            }
        });

        // Replace generic alert() window with an informational theme-friendly custom modal popup
        await ctx.showCustomModal({
            title: "Configuration Saved",
            inputs: [],
            okLabel: "Acknowledged",
            cancelLabel: ""
        });
    });
}